--- # 문서의 시작

excluded:
  - Pods
  - BeaMin-iOS/AppDelegate.swift
included:
  - BeaMin-iOS
analyzer_rules:
  - unused_declaration
  - unused_import
# 기본 규칙이 아닌 규칙들을 활성화
opt_in_rules:
  - sorted_imports
# 디폴트로 활성화되어있는 규칙 중 비활성화할 규칙을 정하는 키워드

# Customized Configurable Rules
sorted_imports: error


... # 문서의 끝

