name: SwiftLint

on:
  pull_request:
    paths:
      - '.github/workflows/swiftlint.yml'
      - '.swiftlint.yml'
      - '**/*.swift'

jobs:
  SwiftLint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Fetch base ref
        run: |
          git fetch --prune --no-tags --depth=1 origin +refs/heads/${{ github.base_ref }}:refs/heads/${{ github.base_ref }}
      - name: GitHub Action for SwiftLint (Only files changed in the PR)
        uses: ezraberch/action-swiftlint@3.2.3
        env:
          DIFF_BASE: ${{ github.base_ref }}
          DIFF_HEAD: HEAD
          
      - name: Add PR Comment
        if: ${{ success() }}
        uses: mshick/add-pr-comment@v1
        with:
          message: |
           ## All File Checked ✅
           | ✅ 	| Auto Pull Request SwiftLint Success!!!! 	|
           |---	|----------------------------------------------	|
          repo-token: ${{ secrets.ACCESS_TOKEN }}
          repo-token-user-login: 'github-actions[bot]' # The user.login for temporary GitHub tokens
          allow-repeats: false # This is the default
